[tool.poetry]
name = "dynamic-prompts"
version = "0.1.0"
description = ""
authors = ["Adi Eyal <adi@clearforest.io>"]
readme = "README.md"
packages = [{include = "dynamicprompts"}]

[tool.poetry.dependencies]
python = "^3.10"
pyparsing = "^3.0.9"
requests = "^2.28.1"
tqdm = "^4.64.1"
jinja2 = "^3.1.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = [
  "dynamicprompts"
]

